CREATE TABLE IF NOT EXISTS images (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  type VARCHAR(25) NOT NULL,
  description VARCHAR(255) NOT NULL,
  taille VARCHAR(255) NOT NULL,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS project (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  nomDuProjet VARCHAR(100),
  lien VARCHAR(255),
  imageID INT,
  FOREIGN KEY (imageID) REFERENCES images(id)
);

CREATE TABLE IF NOT EXISTS pageProjet (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  description VARCHAR(1024),
  lien VARCHAR(255),
  imageID INT,
  FOREIGN KEY (imageID) REFERENCES images(id)
);

CREATE TABLE IF NOT EXISTS pages (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  zonePage INT NOT NULL,
  contenu VARCHAR(255) NOT NULL,
  imageID INT,
  FOREIGN KEY (imageID) REFERENCES images(id)
);